name: taskme
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  google_fonts: ^6.2.1
  uuid: ^4.4.0
  intl: ^0.19.0

  # Updated to 18.x
  flutter_local_notifications: ^18.0.1

  path_provider: ^2.0.9
  cupertino_icons: ^1.0.2
  fl_chart: ^0.69.0
  numberpicker: ^2.1.1
  timezone: ^0.9.0
  permission_handler: ^11.3.1
  smooth_page_indicator: ^1.2.0
  flutter_svg: any
  flutter_bloc: ^8.0.0
  wheel_chooser: ^1.1.2
  flutter_timezone: ^3.0.1
  rive: ^0.13.12
  flutter_animate: ^4.1.1+1
  confetti: ^0.7.0
  flutter_staggered_animations: ^1.0.0
  google_sign_in: ^6.2.2

  # Make sure these match the latest versions
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0

  googleapis: ^13.1.0
  googleapis_auth: ^1.5.1
  http: ^1.1.0
  flutter_phoenix: ^1.1.1
  social_login_buttons: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  # You can also update this if you like:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_fore.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/icon_fore.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon_fore.png
    - assets/alarm.mp3
